using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleDiceSimulator
{
    class Program
    {
        static void Main(string[] args)
        {
            // Declare variables
            Random randDice = new Random(); // A random object to simulate a dice
            const int SIDE_OF_DICE = 6;     // the number of sides of a dice
            int userDice;                   
            int computerDice;               
            int userWins = 0;               
            int computerWins = 0;           
            int ties = 0;                   
            string answer = "YES";          

            // Rolling dice simulation: both user and computer action are actually generated by randDice, a Random object
            while (answer == "YES")
            {
                int userDiceSum = 0;        
                int computerDiceSum = 0;    
                Console.WriteLine("\n\t\tDice 1\tDice 2");

                // User's move
                Console.Write("User\t\t"); // Display who is playing
                for (int i = 1; i <= 2; i++)
                {
                    userDice = randDice.Next(SIDE_OF_DICE) + 1;                    
                    Console.Write(userDice + "\t");            
                    userDiceSum += userDice;
                }

                // computer's move
                Console.Write("\nComputer\t");  // Display who is playing
                for (int j = 1; j <= 2; j++)
                {
                    computerDice = randDice.Next(SIDE_OF_DICE) + 1;
                    Console.Write(computerDice + "\t");
                    computerDiceSum += computerDice;
                }

                // Display the sum of dice value for each roll
                Console.WriteLine("\n-------------------------------");     // Insert a break line
                Console.WriteLine("Your sum: " + userDiceSum + "\tComputer sum: " + computerDiceSum);

                // Determine the winner in each round 
                if (userDiceSum > computerDiceSum)
                {
                    userWins++;
                }   
                else if (userDiceSum < computerDiceSum)
                {
                    computerWins++;
                }   
                else
                {
                    ties++;
                }   

                // Ask user to enter Yes or No to continue the game
                Console.WriteLine("Do you want to play again?(Yes/No)"); 
                answer = Console.ReadLine().ToUpper();
                
                // Validate user's answer
                while (answer != "YES" && answer != "NO")
                {
                   Console.WriteLine("Enter Yes or No to continue.");
                   answer = Console.ReadLine().ToUpper();
                }                
            }

            // Display the final result
            Console.WriteLine("\n-------------------------------");     // Insert a break line
            Console.WriteLine("You won: " + userWins + "\tComputer won: " + computerWins + "\t\tTies: " + ties);

            // Write the result into a .txt file when user chooses not to play game
            try
            {
                System.IO.StreamWriter outputFile = new System.IO.StreamWriter("game_results.txt");
                outputFile.WriteLine("You won " + userWins);
                outputFile.WriteLine("Computer won " + computerWins);
                outputFile.WriteLine("Game ties in " + ties);
                outputFile.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
          
            Console.ReadLine();
        }  
    }
}
